{"name": "test_login_00001", "status": "failed", "statusDetails": {"message": "AssertionError: Expected <True>, but was not.", "trace": "self = <test_login.TestLogin testMethod=test_login_00001>, username = 'admin'\npassword = 'admin'\n\n    @allure.testcase(\"Login Test\")\n    @allure.description(\"Testing the login functionality\")\n    @file_data(\"..//..//datafiles//login.json\")\n    #@pytest.mark.run(1)\n    def test_login(self, username,password):\n        self.login.enter_username(username)\n        self.login.enter_password(password)\n        self.login.click_submit_button()\n>       self.login.check_login_successfull()   ##asserting using the assertpy library\n\ntests\\test_individual\\test_login.py:30: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.page_login.login_page.Login object at 0x00000279DAD554F0>\n\n    @allure.step(\"Check if the success message is displayed\")\n    def check_login_successfull(self):\n>       assert_that(self.isElementDisplayed(self.lp.success_message)).is_true()\nE       AssertionError: Expected <True>, but was not.\n\npages\\page_login\\login_page.py:29: AssertionError"}, "description": "Testing the login functionality", "steps": [{"name": "Enter the username", "status": "passed", "parameters": [{"name": "username", "value": "'admin'"}], "start": 1627160457585, "stop": 1627160457659}, {"name": "Enter the password", "status": "passed", "parameters": [{"name": "password", "value": "'admin'"}], "start": 1627160457659, "stop": 1627160457683}, {"name": "Click on Submit button", "status": "passed", "start": 1627160457683, "stop": 1627160458648}, {"name": "Check if the success message is displayed", "status": "failed", "statusDetails": {"message": "AssertionError: Expected <True>, but was not.\n", "trace": "  File \"c:\\users\\atique.shaikh\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\atique.shaikh\\PycharmProjects\\Python - Framework\\Selenium\\git-selenium-framework2\\pages\\page_login\\login_page.py\", line 29, in check_login_successfull\n    assert_that(self.isElementDisplayed(self.lp.success_message)).is_true()\n  File \"c:\\users\\atique.shaikh\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\assertpy\\base.py\", line 254, in is_true\n    self.error('Expected <True>, but was not.')\n  File \"c:\\users\\atique.shaikh\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\assertpy\\assertpy.py\", line 433, in error\n    raise AssertionError(out)\n"}, "start": 1627160458648, "stop": 1627160469115}], "attachments": [{"name": "screenshot", "source": "0c722d60-4962-441c-a880-eaa1cbabb894-attachment.png", "type": "image/png"}, {"name": "log", "source": "e969e3c3-c41f-4bae-a50a-c601c51e2092-attachment.txt", "type": "text/plain"}], "start": 1627160457585, "stop": 1627160469115, "uuid": "1bf66f8f-314a-477a-8817-bc5e91711496", "historyId": "ea9b5993de0e892b66714dfb8e89b2be", "testCaseId": "1c776c83d7b5dc97e9de905730671416", "fullName": "tests.test_individual.test_login.TestLogin#test_login_00001", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('oneTimeSetup')"}, {"name": "parentSuite", "value": "tests.test_individual"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "CPX-5HW8LFP40FY"}, {"name": "thread", "value": "18288-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_individual.test_login"}], "links": [{"type": "test_case", "url": "Login Test", "name": "Login Test"}]}